### ISSUE TITLE
How to testing models using rspec/test_unit ?

### ISSUE THREAD

**Issue by ricardopacheco** [ruby-oembed/ruby-oembed#64]
Models with embed are leaving my suite tests slow!

**Comment by metavida** [comment]
Just to be clear, are you saying that A) the tests for this gem are slow, or that B) the tests in your own codebase that make ombed requests are slow?

We use [the VCR gem](https://github.com/vcr/vcr) to keep the tests built in to this gem as fast as possible. With VCR, HTTP(S) responses only hit the open internet the first time they're run & then are saved into local JSON files so that subsequent test runs don't have to make actual external requests. In our case we actually commit these JSON files to the codebase so that even our CI tool can benefit from the speed boost. As an added benefit, you also won't get false test failures if a 3rd party service is offline & you can also run your test suite offline.

**Comment by ricardopacheco** [comment]
the tests in your own codebase that make ombed requests are slow!

**Comment by ricardopacheco** [comment]
@metavida is possible utilize mocks/stubs instead of VC? If yes, how to?

**Comment by metavida** [comment]
Sorry, I don't have enough time to help you trouble-shoot this. Hopefully you've figured out a way to use a library like `VCR` to speed up your tests that are/were making HTTP requests.
